<?php include( "header.php"); ?>
<?php include( "_objects/slide_menu.php"); ?>
<?php include( "_objects/hero.php"); ?>
<?php include( "_objects/status.php"); ?>
<?php //include( "_objects/about.php"); ?>
<?php include( "_objects/schedule.php"); ?>
<?php //include( "_objects/catering.php"); ?>
<?php include( "_objects/social.php"); ?>
<?php include( "_objects/media.php"); ?>
<?php include( "_objects/contact.php"); ?>
<?php include( "footer.php"); ?>